server:
  port: 8082

spring:
  application:
    name: kafka-consumer-2
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    consumer:
      group-id: grupo-consumer-2

kafka:
  topic:
    name: mensagens-projeto

logging:
  level:
    root: INFO
    com.projeto.faculdade: DEBUG
    org.apache.kafka: WARN